# Generated by Django 4.2.7 on 2023-12-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_new_backimage_alter_new_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
