# Generated by Django 4.2.7 on 2023-11-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_news_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='filed_test',
        ),
    ]
