# Generated by Django 4.2.7 on 2023-11-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_new_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='backImage',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='field_name',
            field=models.ImageField(upload_to=''),
        ),
    ]
